### ISSUE TITLE
kernel build fail

### ISSUE THREAD

**Issue by scheich** [zwliew/android_kernel_xiaomi_msm8937#4]
Compiled everything from scratch (with LineageOS sources) but the build hangs here:

> target thumb C++: libsdmcore_32 <= hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp
target thumb C++: libsdmcore_32 <= hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:521:51: error: use of undeclared identifier 'MDP_RGBA_1010102'; did you mean 'MDP_RGBA_5551'?
  case kFormatRGBA1010102:              *target = MDP_RGBA_1010102;      break;
                                                  ^~~~~~~~~~~~~~~~
                                                  MDP_RGBA_5551
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:175:2: note: 'MDP_RGBA_5551' declared here
        MDP_RGBA_5551,  /*RGBA 5551*/
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:522:51: error: use of undeclared identifier 'MDP_ARGB_2101010'; did you mean 'MDP_ARGB_1555'?
  case kFormatARGB2101010:              *target = MDP_ARGB_2101010;      break;
                                                  ^~~~~~~~~~~~~~~~
                                                  MDP_ARGB_1555
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:174:2: note: 'MDP_ARGB_1555' declared here
        MDP_ARGB_1555,  /*ARGB 1555*/
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:523:51: error: use of undeclared identifier 'MDP_RGBX_1010102'
  case kFormatRGBX1010102:              *target = MDP_RGBX_1010102;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:524:51: error: use of undeclared identifier 'MDP_XRGB_2101010'
  case kFormatXRGB2101010:              *target = MDP_XRGB_2101010;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:525:51: error: use of undeclared identifier 'MDP_BGRA_1010102'
  case kFormatBGRA1010102:              *target = MDP_BGRA_1010102;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:526:51: error: use of undeclared identifier 'MDP_ABGR_2101010'
  case kFormatABGR2101010:              *target = MDP_ABGR_2101010;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:527:51: error: use of undeclared identifier 'MDP_BGRX_1010102'
  case kFormatBGRX1010102:              *target = MDP_BGRX_1010102;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:528:51: error: use of undeclared identifier 'MDP_XBGR_2101010'
  case kFormatXBGR2101010:              *target = MDP_XBGR_2101010;      break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:529:51: error: use of undeclared identifier 'MDP_RGBA_1010102_UBWC'; did you mean 'MDP_RGBA_8888_UBWC'?
  case kFormatRGBA1010102Ubwc:          *target = MDP_RGBA_1010102_UBWC; break;
                                                  ^~~~~~~~~~~~~~~~~~~~~
                                                  MDP_RGBA_8888_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:179:2: note: 'MDP_RGBA_8888_UBWC' declared here
        MDP_RGBA_8888_UBWC,
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:530:51: error: use of undeclared identifier 'MDP_RGBX_1010102_UBWC'; did you mean 'MDP_RGBX_8888_UBWC'?
  case kFormatRGBX1010102Ubwc:          *target = MDP_RGBX_1010102_UBWC; break;
                                                  ^~~~~~~~~~~~~~~~~~~~~
                                                  MDP_RGBX_8888_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:181:2: note: 'MDP_RGBX_8888_UBWC' declared here
        MDP_RGBX_8888_UBWC,
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:531:51: error: use of undeclared identifier 'MDP_Y_CBCR_H2V2_P010'
  case kFormatYCbCr420P010:             *target = MDP_Y_CBCR_H2V2_P010;  break;
                                                  ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_device.cpp:532:51: error: use of undeclared identifier 'MDP_Y_CBCR_H2V2_TP10_UBWC'; did you mean 'MDP_Y_CBCR_H2V2_UBWC'?
  case kFormatYCbCr420TP10Ubwc:         *target = MDP_Y_CBCR_H2V2_TP10_UBWC; break;
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                  MDP_Y_CBCR_H2V2_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:180:2: note: 'MDP_Y_CBCR_H2V2_UBWC' declared here
        MDP_Y_CBCR_H2V2_UBWC,
        ^
target thumb C++: libsdmcore_32 <= hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_hdmi.cpp
12 errors generated.
build/core/binary.mk:730: die Regel für Ziel „/home/philipp/android/system/out/target/product/land/obj_arm/SHARED_LIBRARIES/libsdmcore_intermediates/fb/hw_device.o“ scheiterte
make: *** [/home/philipp/android/system/out/target/product/land/obj_arm/SHARED_LIBRARIES/libsdmcore_intermediates/fb/hw_device.o] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet...
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:460:8: error: use of undeclared identifier 'MDP_RGBA_1010102'; did you mean 'MDP_RGBA_5551'?
  case MDP_RGBA_1010102:           return kFormatRGBA1010102;
       ^~~~~~~~~~~~~~~~
       MDP_RGBA_5551
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:175:2: note: 'MDP_RGBA_5551' declared here
        MDP_RGBA_5551,  /*RGBA 5551*/
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:461:8: error: use of undeclared identifier 'MDP_ARGB_2101010'; did you mean 'MDP_ARGB_1555'?
  case MDP_ARGB_2101010:           return kFormatARGB2101010;
       ^~~~~~~~~~~~~~~~
       MDP_ARGB_1555
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:174:2: note: 'MDP_ARGB_1555' declared here
        MDP_ARGB_1555,  /*ARGB 1555*/
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:462:8: error: use of undeclared identifier 'MDP_RGBX_1010102'
  case MDP_RGBX_1010102:           return kFormatRGBX1010102;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:463:8: error: use of undeclared identifier 'MDP_XRGB_2101010'
  case MDP_XRGB_2101010:           return kFormatXRGB2101010;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:464:8: error: use of undeclared identifier 'MDP_BGRA_1010102'
  case MDP_BGRA_1010102:           return kFormatBGRA1010102;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:465:8: error: use of undeclared identifier 'MDP_ABGR_2101010'
  case MDP_ABGR_2101010:           return kFormatABGR2101010;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:466:8: error: use of undeclared identifier 'MDP_BGRX_1010102'
  case MDP_BGRX_1010102:           return kFormatBGRX1010102;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:467:8: error: use of undeclared identifier 'MDP_XBGR_2101010'
  case MDP_XBGR_2101010:           return kFormatXBGR2101010;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:468:8: error: use of undeclared identifier 'MDP_RGBA_1010102_UBWC'; did you mean 'MDP_RGBA_8888_UBWC'?
  case MDP_RGBA_1010102_UBWC:      return kFormatRGBA1010102Ubwc;
       ^~~~~~~~~~~~~~~~~~~~~
       MDP_RGBA_8888_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:179:2: note: 'MDP_RGBA_8888_UBWC' declared here
        MDP_RGBA_8888_UBWC,
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:469:8: error: use of undeclared identifier 'MDP_RGBX_1010102_UBWC'; did you mean 'MDP_RGBX_8888_UBWC'?
  case MDP_RGBX_1010102_UBWC:      return kFormatRGBX1010102Ubwc;
       ^~~~~~~~~~~~~~~~~~~~~
       MDP_RGBX_8888_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:181:2: note: 'MDP_RGBX_8888_UBWC' declared here
        MDP_RGBX_8888_UBWC,
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:470:8: error: use of undeclared identifier 'MDP_Y_CBCR_H2V2_P010'
  case MDP_Y_CBCR_H2V2_P010:       return kFormatYCbCr420P010;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:471:8: error: use of undeclared identifier 'MDP_Y_CBCR_H2V2_TP10_UBWC'; did you mean 'MDP_Y_CBCR_H2V2_UBWC'?
  case MDP_Y_CBCR_H2V2_TP10_UBWC:  return kFormatYCbCr420TP10Ubwc;
       ^~~~~~~~~~~~~~~~~~~~~~~~~
       MDP_Y_CBCR_H2V2_UBWC
/home/philipp/android/system/out/target/product/land/obj/KERNEL_OBJ/usr/include/linux/msm_mdp.h:180:2: note: 'MDP_Y_CBCR_H2V2_UBWC' declared here
        MDP_Y_CBCR_H2V2_UBWC,
        ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:460:8: error: duplicate case value 'MDP_RGBA_5551'
  case MDP_RGBA_1010102:           return kFormatRGBA1010102;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:438:8: note: previous case defined here
  case MDP_RGBA_5551:              return kFormatRGBA5551;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:468:8: error: duplicate case value 'MDP_RGBA_8888_UBWC'
  case MDP_RGBA_1010102_UBWC:      return kFormatRGBA1010102Ubwc;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:444:8: note: previous case defined here
  case MDP_RGBA_8888_UBWC:         return kFormatRGBA8888Ubwc;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:471:8: error: duplicate case value 'MDP_Y_CBCR_H2V2_UBWC'
  case MDP_Y_CBCR_H2V2_TP10_UBWC:  return kFormatYCbCr420TP10Ubwc;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:457:8: note: previous case defined here
  case MDP_Y_CBCR_H2V2_UBWC:       return kFormatYCbCr420SPVenusUbwc;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:469:8: error: duplicate case value 'MDP_RGBX_8888_UBWC'
  case MDP_RGBX_1010102_UBWC:      return kFormatRGBX1010102Ubwc;
       ^
hardware/qcom/display-caf/msm8937/sdm/libs/core/fb/hw_info.cpp:445:8: note: previous case defined here
  case MDP_RGBX_8888_UBWC:         return kFormatRGBX8888Ubwc;
       ^
16 errors generated.

Do you know, what I'm missing?

**Comment by fedosis** [comment]
https://android.googlesource.com/platform/hardware/qcom/msm8996/+/3902ad9e52afdda29d140db1235ad9c12a0b1203%5E!/
 - this path is for msm8996. Same is for 8937

**Comment by zwliew** [comment]
You're missing my display HAL fork.

**Comment by scheich** [comment]
Ok, thanks, But you removed it (https://github.com/zwliew/android_hardware_qcom_display) a second ago?

**Comment by zwliew** [comment]
Try the latest cm-13.0 kernel instead. I committed a patch that adds the missing definitions.

**Comment by scheich** [comment]
Yes!!! Completed sucessfully, thanks for fixing.

**Comment by fedosis** [comment]
> Yes!!! Completed successfully, thanks for fixing.
U build only kernel or whole rom?

**Comment by scheich** [comment]
Whole rom, but it doesn't boot :D 

Even after changing the boot.img to the latest build from zwliew it stucks on the mi logo.

**Comment by fedosis** [comment]
@scheich 
Can 100% confirm this. 
Stuck at mi logo.
And this is what i searched for a whole day - archive with "Inherit QCOM board fragments"

**Comment by zwliew** [comment]
Seems like I need to bring back my display HAL fork. I was working on getting us to use the Lineage display HAL, but I didn't have time to make it fully work.

**Comment by zwliew** [comment]
Please try the kernel with this HAL now: https://github.com/zwliew/android_hardware_qcom_display/commits/cm-13.0-caf-8937

**Comment by fedosis** [comment]
@zwliew cm-13.0 brunch of kernel?

**Comment by zwliew** [comment]
Yes, of course.

**Comment by fedosis** [comment]
@zwliew ok, thx, starting "brunch land"

**Comment by fedosis** [comment]
Numerous error when trying to build.
Where I can get mk files for /vendor/cm/config?

**Comment by zwliew** [comment]
https://review.lineageos.org/#/c/144744

**Comment by fedosis** [comment]
@zwliew thx. Try to brunch again.

**Comment by fedosis** [comment]
Can someone post correct roomservice.xml?
With or without qcom_display?

**Comment by scheich** [comment]
@zwliew Same, not booting.

**Comment by zwliew** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" />
  <project name="zwliew/android_device_xiaomi_land" path="device/xiaomi/land" />
  <project name="zwliew/android_kernel_xiaomi_msm8937" path="kernel/xiaomi/msm8937" />
  <project name="zwliew/proprietary_vendor_xiaomi" path="vendor/xiaomi" />
  <remove-project name="LineageOS/android_hardware_qcom_display" />
  <project name="zwliew/android_hardware_qcom_display" path="hardware/qcom/display-caf/msm8937" revision="cm-13.0-caf-8937" />
</manifest>

**Comment by fedosis** [comment]
@zwliew thx. Will try build from clear sheet.

**Comment by fedosis** [comment]
Builder w/o errors. Will try to boot.

**Comment by fedosis** [comment]
Booted perfectly. Will test.
@zwliew can I post compiled ROM on 4pda.ru?
People gone crazy while waiting update to 22.12 ROM after kernel source released.

**Comment by Vimalraj1** [comment]
fedosis what did u changed my compiled successfuly but not booted help me

**Comment by zwliew** [comment]
@fedosis I'm fine with it, as long as you give the necessary credits (i.e "Built from zwliew's sources"). I'm not ready to release any builds personally as I want to get more issues fixed before releasing one.

**Comment by fedosis** [comment]
@Vimalraj1
I start from clean repo init, then use roomservice.xml as described above, then download content for vendor/cm from there https://review.lineageos.org/#/c/144744
Then brunch land.
@zwliew thx. all credits belongs to developer)

**Comment by zwliew** [comment]
Also, if you're keeping yourself up-to-date with my device tree sources, make sure to keep yourself up-to-date with https://review.lineageos.org/#/c/144744 as well. I update the change (https://review.lineageos.org/#/c/144744) regularly, so changes in my device tree would likely having dependencies on changes to https://review.lineageos.org/#/c/144744.

**Comment by lea2000** [comment]
@fedosis Could you post the download link also in the xda thread?

**Comment by scheich** [comment]
@fedosis Could you also post the download link to the xda thread?

**Comment by fedosis** [comment]
@zwliew I'll always notice that. 
@scheich OK, all post after put my son asleep.

**Comment by Vimalraj1** [comment]
can you pls ellaborate since im a learner

**Comment by zwliew** [comment]
How to build:

1. Sync LineageOS source to a directory.
2. Add the following to $LINEAGEOS_DIRECTORY/.repo/local_manifests/roomservice.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" />
  <project name="zwliew/android_device_xiaomi_land" path="device/xiaomi/land" />
  <project name="zwliew/android_kernel_xiaomi_msm8937" path="kernel/xiaomi/msm8937" />
  <project name="zwliew/proprietary_vendor_xiaomi" path="vendor/xiaomi" />
  <remove-project name="LineageOS/android_hardware_qcom_display" />
  <project name="zwliew/android_hardware_qcom_display" path="hardware/qcom/display-caf/msm8937" revision="cm-13.0-caf-8937" />
</manifest>
```
3. Cherry-pick https://review.lineageos.org/#/c/144744
4. Build with brunch.

**Comment by Vimalraj1** [comment]
im trying to compile bliss

**Comment by alexstsv2** [comment]
Goodix work. Only goodix.
https://github.com/alexstsv2

**Comment by zwliew** [comment]
Thanks for the work! I'll take a look soon.

**Comment by fedosis** [comment]
@zwliew can you tell us any good news about developing next build?

**Comment by Vimalraj1** [comment]
Bro stuck on mi logo What to do now??

**Comment by flsagarjain** [comment]
Anyone can help with this?

hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:763:49: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
            y_meta_stride = VENUS_Y_META_STRIDE(COLOR_FMT_NV12_UBWC, width);
                                                ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:764:52: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
            y_meta_height = VENUS_Y_META_SCANLINES(COLOR_FMT_NV12_UBWC, height);
                                                   ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:771:50: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
            c_meta_stride = VENUS_UV_META_STRIDE(COLOR_FMT_NV12_UBWC, width);
                                                 ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:772:53: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
            c_meta_height = VENUS_UV_META_SCANLINES(COLOR_FMT_NV12_UBWC, height);
                                                    ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:780:46: error: use of undeclared identifier 'COLOR_FMT_NV12_UBWC'
            ycbcr->cstride = VENUS_UV_STRIDE(COLOR_FMT_NV12_UBWC, width);
                                             ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:936:39: error: unused parameter 'width' [-Werror,-Wunused-parameter]
static void getUBwcWidthAndHeight(int width, int height, int format,
                                      ^
hardware/qcom/display-caf/msm8937/libgralloc/alloc_controller.cpp:936:50: error: unused parameter 'height' [-Werror,-Wunused-parameter]
static void getUBwcWidthAndHeight(int width, int height, int format,

**Comment by irfan2406** [comment]
Display-caf error, try updated roms
