### ISSUE TITLE
ean can pls ellaborate since im a learner

### ISSUE THREAD

**Issue by Vimalraj1** [zwliew/android_kernel_xiaomi_msm8937#6]

**Comment by zwliew** [comment]
How to build:

1. Sync LineageOS source to a directory.
2. Add the following to $LINEAGEOS_DIRECTORY/.repo/local_manifests/roomservice.xml:
`
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" />
  <project name="zwliew/android_device_xiaomi_land" path="device/xiaomi/land" />
  <project name="zwliew/android_kernel_xiaomi_msm8937" path="kernel/xiaomi/msm8937" />
  <project name="zwliew/proprietary_vendor_xiaomi" path="vendor/xiaomi" />
  <remove-project name="LineageOS/android_hardware_qcom_display" />
  <project name="zwliew/android_hardware_qcom_display" path="hardware/qcom/display-caf/msm8937" revision="cm-13.0-caf-8937" />
</manifest>`
3. Build with brunch.
